namespace WordClockTaskbar.Helpers;

// Maps a Windows time zone ID to its representative ISO 3166-1 alpha-2 country
// code. Generated from the Unicode CLDR windowsZones.xml (default "001" zone).
// Used to pick the flag image for each timezone; unmapped IDs (e.g. raw UTC
// offsets) fall back to the text label.
public static class TimezoneCountry
{
    private static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        { "AUS Central Standard Time", "au" },
        { "AUS Eastern Standard Time", "au" },
        { "Afghanistan Standard Time", "af" },
        { "Alaskan Standard Time", "us" },
        { "Aleutian Standard Time", "us" },
        { "Altai Standard Time", "ru" },
        { "Arab Standard Time", "sa" },
        { "Arabian Standard Time", "ae" },
        { "Arabic Standard Time", "iq" },
        { "Argentina Standard Time", "ar" },
        { "Astrakhan Standard Time", "ru" },
        { "Atlantic Standard Time", "ca" },
        { "Aus Central W. Standard Time", "au" },
        { "Azerbaijan Standard Time", "az" },
        { "Azores Standard Time", "pt" },
        { "Bahia Standard Time", "br" },
        { "Bangladesh Standard Time", "bd" },
        { "Belarus Standard Time", "by" },
        { "Bougainville Standard Time", "pg" },
        { "Canada Central Standard Time", "ca" },
        { "Cape Verde Standard Time", "cv" },
        { "Caucasus Standard Time", "am" },
        { "Cen. Australia Standard Time", "au" },
        { "Central America Standard Time", "gt" },
        { "Central Asia Standard Time", "kg" },
        { "Central Brazilian Standard Time", "br" },
        { "Central Europe Standard Time", "hu" },
        { "Central European Standard Time", "pl" },
        { "Central Pacific Standard Time", "sb" },
        { "Central Standard Time", "us" },
        { "Central Standard Time (Mexico)", "mx" },
        { "Chatham Islands Standard Time", "nz" },
        { "China Standard Time", "cn" },
        { "Cuba Standard Time", "cu" },
        { "E. Africa Standard Time", "ke" },
        { "E. Australia Standard Time", "au" },
        { "E. Europe Standard Time", "md" },
        { "E. South America Standard Time", "br" },
        { "Easter Island Standard Time", "cl" },
        { "Eastern Standard Time", "us" },
        { "Eastern Standard Time (Mexico)", "mx" },
        { "Egypt Standard Time", "eg" },
        { "Ekaterinburg Standard Time", "ru" },
        { "FLE Standard Time", "ua" },
        { "Fiji Standard Time", "fj" },
        { "GMT Standard Time", "gb" },
        { "GTB Standard Time", "ro" },
        { "Georgian Standard Time", "ge" },
        { "Greenland Standard Time", "gl" },
        { "Greenwich Standard Time", "is" },
        { "Haiti Standard Time", "ht" },
        { "Hawaiian Standard Time", "us" },
        { "India Standard Time", "in" },
        { "Iran Standard Time", "ir" },
        { "Israel Standard Time", "il" },
        { "Jordan Standard Time", "jo" },
        { "Kaliningrad Standard Time", "ru" },
        { "Korea Standard Time", "kr" },
        { "Libya Standard Time", "ly" },
        { "Line Islands Standard Time", "ki" },
        { "Lord Howe Standard Time", "au" },
        { "Magadan Standard Time", "ru" },
        { "Magallanes Standard Time", "cl" },
        { "Marquesas Standard Time", "pf" },
        { "Mauritius Standard Time", "mu" },
        { "Middle East Standard Time", "lb" },
        { "Montevideo Standard Time", "uy" },
        { "Morocco Standard Time", "ma" },
        { "Mountain Standard Time", "us" },
        { "Mountain Standard Time (Mexico)", "mx" },
        { "Myanmar Standard Time", "mm" },
        { "N. Central Asia Standard Time", "ru" },
        { "Namibia Standard Time", "na" },
        { "Nepal Standard Time", "np" },
        { "New Zealand Standard Time", "nz" },
        { "Newfoundland Standard Time", "ca" },
        { "Norfolk Standard Time", "nf" },
        { "North Asia East Standard Time", "ru" },
        { "North Asia Standard Time", "ru" },
        { "North Korea Standard Time", "kp" },
        { "Omsk Standard Time", "ru" },
        { "Pacific SA Standard Time", "cl" },
        { "Pacific Standard Time", "us" },
        { "Pacific Standard Time (Mexico)", "mx" },
        { "Pakistan Standard Time", "pk" },
        { "Paraguay Standard Time", "py" },
        { "Qyzylorda Standard Time", "kz" },
        { "Romance Standard Time", "fr" },
        { "Russia Time Zone 10", "ru" },
        { "Russia Time Zone 11", "ru" },
        { "Russia Time Zone 3", "ru" },
        { "Russian Standard Time", "ru" },
        { "SA Eastern Standard Time", "gf" },
        { "SA Pacific Standard Time", "co" },
        { "SA Western Standard Time", "bo" },
        { "SE Asia Standard Time", "th" },
        { "Saint Pierre Standard Time", "pm" },
        { "Sakhalin Standard Time", "ru" },
        { "Samoa Standard Time", "ws" },
        { "Sao Tome Standard Time", "st" },
        { "Saratov Standard Time", "ru" },
        { "Singapore Standard Time", "sg" },
        { "South Africa Standard Time", "za" },
        { "South Sudan Standard Time", "ss" },
        { "Sri Lanka Standard Time", "lk" },
        { "Sudan Standard Time", "sd" },
        { "Syria Standard Time", "sy" },
        { "Taipei Standard Time", "tw" },
        { "Tasmania Standard Time", "au" },
        { "Tocantins Standard Time", "br" },
        { "Tokyo Standard Time", "jp" },
        { "Tomsk Standard Time", "ru" },
        { "Tonga Standard Time", "to" },
        { "Transbaikal Standard Time", "ru" },
        { "Turkey Standard Time", "tr" },
        { "Turks And Caicos Standard Time", "tc" },
        { "US Eastern Standard Time", "us" },
        { "US Mountain Standard Time", "us" },
        { "Ulaanbaatar Standard Time", "mn" },
        { "Venezuela Standard Time", "ve" },
        { "Vladivostok Standard Time", "ru" },
        { "Volgograd Standard Time", "ru" },
        { "W. Australia Standard Time", "au" },
        { "W. Central Africa Standard Time", "ng" },
        { "W. Europe Standard Time", "de" },
        { "W. Mongolia Standard Time", "mn" },
        { "West Asia Standard Time", "uz" },
        { "West Bank Standard Time", "ps" },
        { "West Pacific Standard Time", "pg" },
        { "Yakutsk Standard Time", "ru" },
        { "Yukon Standard Time", "ca" },
    };

    // Returns lowercase ISO2 (e.g. "us") or null if unknown.
    public static string? GetIso2(string timezoneId)
        => Map.TryGetValue(timezoneId, out var iso) ? iso : null;
}
